//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WBZ.Properties {
    
    
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.VisualStudio.Editors.SettingsDesigner.SettingsSingleFileGenerator", "16.8.1.0")]
    internal sealed partial class Settings : global::System.Configuration.ApplicationSettingsBase {
        
        private static Settings defaultInstance = ((Settings)(global::System.Configuration.ApplicationSettingsBase.Synchronized(new Settings())));
        
        public static Settings Default {
            get {
                return defaultInstance;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string apiUrl {
            get {
                return ((string)(this["apiUrl"]));
            }
            set {
                this["apiUrl"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string userName {
            get {
                return ((string)(this["userName"]));
            }
            set {
                this["userName"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string userPass {
            get {
                return ((string)(this["userPass"]));
            }
            set {
                this["userPass"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string dbName {
            get {
                return ((string)(this["dbName"]));
            }
            set {
                this["dbName"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("True")]
        public bool rememberMe {
            get {
                return ((bool)(this["rememberMe"]));
            }
            set {
                this["rememberMe"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("1")]
        public byte config_TitleBarStyle {
            get {
                return ((byte)(this["config_TitleBarStyle"]));
            }
            set {
                this["config_TitleBarStyle"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("12")]
        public double iSize {
            get {
                return ((double)(this["iSize"]));
            }
            set {
                this["iSize"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("#FF444444")]
        public string config_Admin_PanelColor {
            get {
                return ((string)(this["config_Admin_PanelColor"]));
            }
            set {
                this["config_Admin_PanelColor"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("#FF33AAEE")]
        public string config_Documents_PanelColor {
            get {
                return ((string)(this["config_Documents_PanelColor"]));
            }
            set {
                this["config_Documents_PanelColor"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool columns_DocumentsList_ID {
            get {
                return ((bool)(this["columns_DocumentsList_ID"]));
            }
            set {
                this["columns_DocumentsList_ID"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("True")]
        public bool columns_DocumentsList_StoreName {
            get {
                return ((bool)(this["columns_DocumentsList_StoreName"]));
            }
            set {
                this["columns_DocumentsList_StoreName"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("True")]
        public bool columns_DocumentsList_Type {
            get {
                return ((bool)(this["columns_DocumentsList_Type"]));
            }
            set {
                this["columns_DocumentsList_Type"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("True")]
        public bool columns_DocumentsList_Name {
            get {
                return ((bool)(this["columns_DocumentsList_Name"]));
            }
            set {
                this["columns_DocumentsList_Name"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("True")]
        public bool columns_DocumentsList_PositionsCount {
            get {
                return ((bool)(this["columns_DocumentsList_PositionsCount"]));
            }
            set {
                this["columns_DocumentsList_PositionsCount"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("True")]
        public bool columns_DocumentsList_Weight {
            get {
                return ((bool)(this["columns_DocumentsList_Weight"]));
            }
            set {
                this["columns_DocumentsList_Weight"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("True")]
        public bool columns_DocumentsList_Cost {
            get {
                return ((bool)(this["columns_DocumentsList_Cost"]));
            }
            set {
                this["columns_DocumentsList_Cost"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("True")]
        public bool columns_DocumentsList_DateIssue {
            get {
                return ((bool)(this["columns_DocumentsList_DateIssue"]));
            }
            set {
                this["columns_DocumentsList_DateIssue"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool columns_StoresList_ID {
            get {
                return ((bool)(this["columns_StoresList_ID"]));
            }
            set {
                this["columns_StoresList_ID"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("True")]
        public bool columns_StoresList_Codename {
            get {
                return ((bool)(this["columns_StoresList_Codename"]));
            }
            set {
                this["columns_StoresList_Codename"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("True")]
        public bool columns_StoresList_Name {
            get {
                return ((bool)(this["columns_StoresList_Name"]));
            }
            set {
                this["columns_StoresList_Name"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool columns_StoresList_Postcode {
            get {
                return ((bool)(this["columns_StoresList_Postcode"]));
            }
            set {
                this["columns_StoresList_Postcode"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool columns_StoresList_City {
            get {
                return ((bool)(this["columns_StoresList_City"]));
            }
            set {
                this["columns_StoresList_City"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool columns_StoresList_Address {
            get {
                return ((bool)(this["columns_StoresList_Address"]));
            }
            set {
                this["columns_StoresList_Address"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("True")]
        public bool columns_StoresList_Amount {
            get {
                return ((bool)(this["columns_StoresList_Amount"]));
            }
            set {
                this["columns_StoresList_Amount"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("True")]
        public bool columns_StoresList_Reserved {
            get {
                return ((bool)(this["columns_StoresList_Reserved"]));
            }
            set {
                this["columns_StoresList_Reserved"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("#FF55DD55")]
        public string config_Articles_PanelColor {
            get {
                return ((string)(this["config_Articles_PanelColor"]));
            }
            set {
                this["config_Articles_PanelColor"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool columns_ArticlesList_ID {
            get {
                return ((bool)(this["columns_ArticlesList_ID"]));
            }
            set {
                this["columns_ArticlesList_ID"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("True")]
        public bool columns_ArticlesList_Codename {
            get {
                return ((bool)(this["columns_ArticlesList_Codename"]));
            }
            set {
                this["columns_ArticlesList_Codename"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("True")]
        public bool columns_ArticlesList_Name {
            get {
                return ((bool)(this["columns_ArticlesList_Name"]));
            }
            set {
                this["columns_ArticlesList_Name"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("True")]
        public bool columns_ArticlesList_EAN {
            get {
                return ((bool)(this["columns_ArticlesList_EAN"]));
            }
            set {
                this["columns_ArticlesList_EAN"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("True")]
        public bool columns_ArticlesList_Measure {
            get {
                return ((bool)(this["columns_ArticlesList_Measure"]));
            }
            set {
                this["columns_ArticlesList_Measure"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("True")]
        public bool columns_ArticlesList_Amount {
            get {
                return ((bool)(this["columns_ArticlesList_Amount"]));
            }
            set {
                this["columns_ArticlesList_Amount"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("True")]
        public bool columns_ArticlesList_Reserved {
            get {
                return ((bool)(this["columns_ArticlesList_Reserved"]));
            }
            set {
                this["columns_ArticlesList_Reserved"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("#FFEEEE55")]
        public string config_Contractors_PanelColor {
            get {
                return ((string)(this["config_Contractors_PanelColor"]));
            }
            set {
                this["config_Contractors_PanelColor"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("#FFEEAA33")]
        public string config_Families_PanelColor {
            get {
                return ((string)(this["config_Families_PanelColor"]));
            }
            set {
                this["config_Families_PanelColor"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("#FFBB88DD")]
        public string config_Stats_PanelColor {
            get {
                return ((string)(this["config_Stats_PanelColor"]));
            }
            set {
                this["config_Stats_PanelColor"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool columns_FamiliesList_ID {
            get {
                return ((bool)(this["columns_FamiliesList_ID"]));
            }
            set {
                this["columns_FamiliesList_ID"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool columns_FamiliesList_Declarant {
            get {
                return ((bool)(this["columns_FamiliesList_Declarant"]));
            }
            set {
                this["columns_FamiliesList_Declarant"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("True")]
        public bool columns_FamiliesList_Lastname {
            get {
                return ((bool)(this["columns_FamiliesList_Lastname"]));
            }
            set {
                this["columns_FamiliesList_Lastname"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("True")]
        public bool columns_FamiliesList_Members {
            get {
                return ((bool)(this["columns_FamiliesList_Members"]));
            }
            set {
                this["columns_FamiliesList_Members"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("True")]
        public bool columns_FamiliesList_City {
            get {
                return ((bool)(this["columns_FamiliesList_City"]));
            }
            set {
                this["columns_FamiliesList_City"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool columns_FamiliesList_Address {
            get {
                return ((bool)(this["columns_FamiliesList_Address"]));
            }
            set {
                this["columns_FamiliesList_Address"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool columns_FamiliesList_Postcode {
            get {
                return ((bool)(this["columns_FamiliesList_Postcode"]));
            }
            set {
                this["columns_FamiliesList_Postcode"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("True")]
        public bool columns_FamiliesList_DonationWeight {
            get {
                return ((bool)(this["columns_FamiliesList_DonationWeight"]));
            }
            set {
                this["columns_FamiliesList_DonationWeight"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("True")]
        public bool columns_FamiliesList_Status {
            get {
                return ((bool)(this["columns_FamiliesList_Status"]));
            }
            set {
                this["columns_FamiliesList_Status"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("True")]
        public bool columns_FamiliesList_DonationLast {
            get {
                return ((bool)(this["columns_FamiliesList_DonationLast"]));
            }
            set {
                this["columns_FamiliesList_DonationLast"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("smtp.gmail.com")]
        public string config_Email_Host {
            get {
                return ((string)(this["config_Email_Host"]));
            }
            set {
                this["config_Email_Host"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("587")]
        public int config_Email_Port {
            get {
                return ((int)(this["config_Email_Port"]));
            }
            set {
                this["config_Email_Port"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("wbz.email.testowy@gmail.com")]
        public string config_Email_Email {
            get {
                return ((string)(this["config_Email_Email"]));
            }
            set {
                this["config_Email_Email"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("COM5")]
        public string config_GSM_com {
            get {
                return ((string)(this["config_GSM_com"]));
            }
            set {
                this["config_GSM_com"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("WBZ, Twoja paczka jest do odebrania. ")]
        public string config_GSM_message {
            get {
                return ((string)(this["config_GSM_message"]));
            }
            set {
                this["config_GSM_message"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string config_Email_Password {
            get {
                return ((string)(this["config_Email_Password"]));
            }
            set {
                this["config_Email_Password"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("wbztest.ddns.net")]
        public string conn_server {
            get {
                return ((string)(this["conn_server"]));
            }
            set {
                this["conn_server"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("5432")]
        public int conn_port {
            get {
                return ((int)(this["conn_port"]));
            }
            set {
                this["conn_port"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("wbz")]
        public string conn_database {
            get {
                return ((string)(this["conn_database"]));
            }
            set {
                this["conn_database"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string conn_userID {
            get {
                return ((string)(this["conn_userID"]));
            }
            set {
                this["conn_userID"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string conn_password {
            get {
                return ((string)(this["conn_password"]));
            }
            set {
                this["conn_password"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("#FFEE5555")]
        public string config_Distributions_PanelColor {
            get {
                return ((string)(this["config_Distributions_PanelColor"]));
            }
            set {
                this["config_Distributions_PanelColor"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool columns_DistributionsList_ID {
            get {
                return ((bool)(this["columns_DistributionsList_ID"]));
            }
            set {
                this["columns_DistributionsList_ID"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("True")]
        public bool columns_DistributionsList_Name {
            get {
                return ((bool)(this["columns_DistributionsList_Name"]));
            }
            set {
                this["columns_DistributionsList_Name"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("True")]
        public bool columns_DistributionsList_FamiliesCount {
            get {
                return ((bool)(this["columns_DistributionsList_FamiliesCount"]));
            }
            set {
                this["columns_DistributionsList_FamiliesCount"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool columns_DistributionsList_MembersCount {
            get {
                return ((bool)(this["columns_DistributionsList_MembersCount"]));
            }
            set {
                this["columns_DistributionsList_MembersCount"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("True")]
        public bool columns_DistributionsList_PositionsCount {
            get {
                return ((bool)(this["columns_DistributionsList_PositionsCount"]));
            }
            set {
                this["columns_DistributionsList_PositionsCount"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("True")]
        public bool columns_DistributionsList_Weight {
            get {
                return ((bool)(this["columns_DistributionsList_Weight"]));
            }
            set {
                this["columns_DistributionsList_Weight"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("True")]
        public bool columns_DistributionsList_DateReal {
            get {
                return ((bool)(this["columns_DistributionsList_DateReal"]));
            }
            set {
                this["columns_DistributionsList_DateReal"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("Segoe UI")]
        public string config_FontFamily {
            get {
                return ((string)(this["config_FontFamily"]));
            }
            set {
                this["config_FontFamily"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("True")]
        public bool UpgradeRequired {
            get {
                return ((bool)(this["UpgradeRequired"]));
            }
            set {
                this["UpgradeRequired"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool columns_UsersList_ID {
            get {
                return ((bool)(this["columns_UsersList_ID"]));
            }
            set {
                this["columns_UsersList_ID"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("True")]
        public bool columns_UsersList_Fullname {
            get {
                return ((bool)(this["columns_UsersList_Fullname"]));
            }
            set {
                this["columns_UsersList_Fullname"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("True")]
        public bool columns_UsersList_Email {
            get {
                return ((bool)(this["columns_UsersList_Email"]));
            }
            set {
                this["columns_UsersList_Email"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("True")]
        public bool columns_UsersList_Phone {
            get {
                return ((bool)(this["columns_UsersList_Phone"]));
            }
            set {
                this["columns_UsersList_Phone"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool columns_LogsList_ID {
            get {
                return ((bool)(this["columns_LogsList_ID"]));
            }
            set {
                this["columns_LogsList_ID"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("True")]
        public bool columns_LogsList_UserFullname {
            get {
                return ((bool)(this["columns_LogsList_UserFullname"]));
            }
            set {
                this["columns_LogsList_UserFullname"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("True")]
        public bool columns_LogsList_Module {
            get {
                return ((bool)(this["columns_LogsList_Module"]));
            }
            set {
                this["columns_LogsList_Module"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("True")]
        public bool columns_LogsList_Obj {
            get {
                return ((bool)(this["columns_LogsList_Obj"]));
            }
            set {
                this["columns_LogsList_Obj"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("True")]
        public bool columns_LogsList_Content {
            get {
                return ((bool)(this["columns_LogsList_Content"]));
            }
            set {
                this["columns_LogsList_Content"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("True")]
        public bool columns_LogsList_DateTime {
            get {
                return ((bool)(this["columns_LogsList_DateTime"]));
            }
            set {
                this["columns_LogsList_DateTime"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("#FFFF69B4")]
        public string config_Attmisc_PanelColor {
            get {
                return ((string)(this["config_Attmisc_PanelColor"]));
            }
            set {
                this["config_Attmisc_PanelColor"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool columns_EmployeesList_ID {
            get {
                return ((bool)(this["columns_EmployeesList_ID"]));
            }
            set {
                this["columns_EmployeesList_ID"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("True")]
        public bool columns_EmployeesList_Fullname {
            get {
                return ((bool)(this["columns_EmployeesList_Fullname"]));
            }
            set {
                this["columns_EmployeesList_Fullname"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool columns_EmployeesList_Department {
            get {
                return ((bool)(this["columns_EmployeesList_Department"]));
            }
            set {
                this["columns_EmployeesList_Department"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool columns_EmployeesList_Position {
            get {
                return ((bool)(this["columns_EmployeesList_Position"]));
            }
            set {
                this["columns_EmployeesList_Position"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("True")]
        public bool columns_EmployeesList_Email {
            get {
                return ((bool)(this["columns_EmployeesList_Email"]));
            }
            set {
                this["columns_EmployeesList_Email"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("True")]
        public bool columns_EmployeesList_Phone {
            get {
                return ((bool)(this["columns_EmployeesList_Phone"]));
            }
            set {
                this["columns_EmployeesList_Phone"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool columns_EmployeesList_Postcode {
            get {
                return ((bool)(this["columns_EmployeesList_Postcode"]));
            }
            set {
                this["columns_EmployeesList_Postcode"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool columns_EmployeesList_City {
            get {
                return ((bool)(this["columns_EmployeesList_City"]));
            }
            set {
                this["columns_EmployeesList_City"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool columns_EmployeesList_Address {
            get {
                return ((bool)(this["columns_EmployeesList_Address"]));
            }
            set {
                this["columns_EmployeesList_Address"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute(@"<?xml version=""1.0"" encoding=""utf-16""?>
<ArrayOfString xmlns:xsi=""http://www.w3.org/2001/XMLSchema-instance"" xmlns:xsd=""http://www.w3.org/2001/XMLSchema"">
  <string>e.lastname</string>
  <string>False</string>
  <string>e.forename</string>
  <string>False</string>
  <string>50</string>
</ArrayOfString>")]
        public global::System.Collections.Specialized.StringCollection sorting_EmployeesList {
            get {
                return ((global::System.Collections.Specialized.StringCollection)(this["sorting_EmployeesList"]));
            }
            set {
                this["sorting_EmployeesList"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute(@"<?xml version=""1.0"" encoding=""utf-16""?>
<ArrayOfString xmlns:xsi=""http://www.w3.org/2001/XMLSchema-instance"" xmlns:xsd=""http://www.w3.org/2001/XMLSchema"">
  <string>u.lastname</string>
  <string>False</string>
  <string>u.forename</string>
  <string>False</string>
  <string>50</string>
</ArrayOfString>")]
        public global::System.Collections.Specialized.StringCollection sorting_UsersList {
            get {
                return ((global::System.Collections.Specialized.StringCollection)(this["sorting_UsersList"]));
            }
            set {
                this["sorting_UsersList"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute(@"<?xml version=""1.0"" encoding=""utf-16""?>
<ArrayOfString xmlns:xsi=""http://www.w3.org/2001/XMLSchema-instance"" xmlns:xsd=""http://www.w3.org/2001/XMLSchema"">
  <string>a.codename</string>
  <string>False</string>
  <string>a.name</string>
  <string>False</string>
  <string>50</string>
</ArrayOfString>")]
        public global::System.Collections.Specialized.StringCollection sorting_ArticlesList {
            get {
                return ((global::System.Collections.Specialized.StringCollection)(this["sorting_ArticlesList"]));
            }
            set {
                this["sorting_ArticlesList"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute(@"<?xml version=""1.0"" encoding=""utf-16""?>
<ArrayOfString xmlns:xsi=""http://www.w3.org/2001/XMLSchema-instance"" xmlns:xsd=""http://www.w3.org/2001/XMLSchema"">
  <string>s.codename</string>
  <string>False</string>
  <string>s.name</string>
  <string>False</string>
  <string>50</string>
</ArrayOfString>")]
        public global::System.Collections.Specialized.StringCollection sorting_StoresList {
            get {
                return ((global::System.Collections.Specialized.StringCollection)(this["sorting_StoresList"]));
            }
            set {
                this["sorting_StoresList"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute(@"<?xml version=""1.0"" encoding=""utf-16""?>
<ArrayOfString xmlns:xsi=""http://www.w3.org/2001/XMLSchema-instance"" xmlns:xsd=""http://www.w3.org/2001/XMLSchema"">
  <string>f.lastname</string>
  <string>False</string>
  <string>f.city</string>
  <string>False</string>
  <string>50</string>
</ArrayOfString>")]
        public global::System.Collections.Specialized.StringCollection sorting_FamiliesList {
            get {
                return ((global::System.Collections.Specialized.StringCollection)(this["sorting_FamiliesList"]));
            }
            set {
                this["sorting_FamiliesList"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute(@"<?xml version=""1.0"" encoding=""utf-16""?>
<ArrayOfString xmlns:xsi=""http://www.w3.org/2001/XMLSchema-instance"" xmlns:xsd=""http://www.w3.org/2001/XMLSchema"">
  <string>d.dateissue</string>
  <string>True</string>
  <string>d.name</string>
  <string>False</string>
  <string>50</string>
</ArrayOfString>")]
        public global::System.Collections.Specialized.StringCollection sorting_DocumentsList {
            get {
                return ((global::System.Collections.Specialized.StringCollection)(this["sorting_DocumentsList"]));
            }
            set {
                this["sorting_DocumentsList"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute(@"<?xml version=""1.0"" encoding=""utf-16""?>
<ArrayOfString xmlns:xsi=""http://www.w3.org/2001/XMLSchema-instance"" xmlns:xsd=""http://www.w3.org/2001/XMLSchema"">
  <string>d.datereal</string>
  <string>True</string>
  <string>d.name</string>
  <string>False</string>
  <string>50</string>
</ArrayOfString>")]
        public global::System.Collections.Specialized.StringCollection sorting_DistributionsList {
            get {
                return ((global::System.Collections.Specialized.StringCollection)(this["sorting_DistributionsList"]));
            }
            set {
                this["sorting_DistributionsList"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute(@"<?xml version=""1.0"" encoding=""utf-16""?>
<ArrayOfString xmlns:xsi=""http://www.w3.org/2001/XMLSchema-instance"" xmlns:xsd=""http://www.w3.org/2001/XMLSchema"">
  <string>l.datetime</string>
  <string>True</string>
  <string>l.id</string>
  <string>True</string>
  <string>50</string>
</ArrayOfString>")]
        public global::System.Collections.Specialized.StringCollection sorting_LogsList {
            get {
                return ((global::System.Collections.Specialized.StringCollection)(this["sorting_LogsList"]));
            }
            set {
                this["sorting_LogsList"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute(@"<?xml version=""1.0"" encoding=""utf-16""?>
<ArrayOfString xmlns:xsi=""http://www.w3.org/2001/XMLSchema-instance"" xmlns:xsd=""http://www.w3.org/2001/XMLSchema"">
  <string>ac.module</string>
  <string>False</string>
  <string>ac.name</string>
  <string>False</string>
  <string>50</string>
</ArrayOfString>")]
        public global::System.Collections.Specialized.StringCollection sorting_AttributesClassesList {
            get {
                return ((global::System.Collections.Specialized.StringCollection)(this["sorting_AttributesClassesList"]));
            }
            set {
                this["sorting_AttributesClassesList"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute(@"<?xml version=""1.0"" encoding=""utf-16""?>
<ArrayOfString xmlns:xsi=""http://www.w3.org/2001/XMLSchema-instance"" xmlns:xsd=""http://www.w3.org/2001/XMLSchema"">
  <string>g.module</string>
  <string>False</string>
  <string>g.name</string>
  <string>False</string>
  <string>50</string>
</ArrayOfString>")]
        public global::System.Collections.Specialized.StringCollection sorting_GroupsList {
            get {
                return ((global::System.Collections.Specialized.StringCollection)(this["sorting_GroupsList"]));
            }
            set {
                this["sorting_GroupsList"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute(@"<?xml version=""1.0"" encoding=""utf-16""?>
<ArrayOfString xmlns:xsi=""http://www.w3.org/2001/XMLSchema-instance"" xmlns:xsd=""http://www.w3.org/2001/XMLSchema"">
  <string>a.module</string>
  <string>False</string>
  <string>a.name</string>
  <string>False</string>
  <string>20</string>
</ArrayOfString>")]
        public global::System.Collections.Specialized.StringCollection sorting_AttachmentsGallery {
            get {
                return ((global::System.Collections.Specialized.StringCollection)(this["sorting_AttachmentsGallery"]));
            }
            set {
                this["sorting_AttachmentsGallery"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool columns_EmployeesList_Icon {
            get {
                return ((bool)(this["columns_EmployeesList_Icon"]));
            }
            set {
                this["columns_EmployeesList_Icon"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool columns_ArticlesList_Icon {
            get {
                return ((bool)(this["columns_ArticlesList_Icon"]));
            }
            set {
                this["columns_ArticlesList_Icon"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool columns_StoresList_Icon {
            get {
                return ((bool)(this["columns_StoresList_Icon"]));
            }
            set {
                this["columns_StoresList_Icon"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool columns_AttributesClassesList_Icon {
            get {
                return ((bool)(this["columns_AttributesClassesList_Icon"]));
            }
            set {
                this["columns_AttributesClassesList_Icon"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool columns_DistributionsList_Icon {
            get {
                return ((bool)(this["columns_DistributionsList_Icon"]));
            }
            set {
                this["columns_DistributionsList_Icon"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool columns_DocumentsList_Icon {
            get {
                return ((bool)(this["columns_DocumentsList_Icon"]));
            }
            set {
                this["columns_DocumentsList_Icon"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool columns_FamiliesList_Icon {
            get {
                return ((bool)(this["columns_FamiliesList_Icon"]));
            }
            set {
                this["columns_FamiliesList_Icon"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool columns_AttributesClassesList_ID {
            get {
                return ((bool)(this["columns_AttributesClassesList_ID"]));
            }
            set {
                this["columns_AttributesClassesList_ID"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("True")]
        public bool columns_AttributesClassesList_Module {
            get {
                return ((bool)(this["columns_AttributesClassesList_Module"]));
            }
            set {
                this["columns_AttributesClassesList_Module"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("True")]
        public bool columns_AttributesClassesList_Name {
            get {
                return ((bool)(this["columns_AttributesClassesList_Name"]));
            }
            set {
                this["columns_AttributesClassesList_Name"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("True")]
        public bool columns_AttributesClassesList_Type {
            get {
                return ((bool)(this["columns_AttributesClassesList_Type"]));
            }
            set {
                this["columns_AttributesClassesList_Type"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool columns_AttributesClassesList_Values {
            get {
                return ((bool)(this["columns_AttributesClassesList_Values"]));
            }
            set {
                this["columns_AttributesClassesList_Values"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool columns_AttributesClassesList_Required {
            get {
                return ((bool)(this["columns_AttributesClassesList_Required"]));
            }
            set {
                this["columns_AttributesClassesList_Required"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute(@"<?xml version=""1.0"" encoding=""utf-16""?>
<ArrayOfString xmlns:xsi=""http://www.w3.org/2001/XMLSchema-instance"" xmlns:xsd=""http://www.w3.org/2001/XMLSchema"">
  <string>a.module</string>
  <string>False</string>
  <string>a.name</string>
  <string>False</string>
  <string>50</string>
</ArrayOfString>")]
        public global::System.Collections.Specialized.StringCollection sorting_AttachmentsList {
            get {
                return ((global::System.Collections.Specialized.StringCollection)(this["sorting_AttachmentsList"]));
            }
            set {
                this["sorting_AttachmentsList"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool columns_AttachmentsList_ID {
            get {
                return ((bool)(this["columns_AttachmentsList_ID"]));
            }
            set {
                this["columns_AttachmentsList_ID"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("True")]
        public bool columns_AttachmentsList_Module {
            get {
                return ((bool)(this["columns_AttachmentsList_Module"]));
            }
            set {
                this["columns_AttachmentsList_Module"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("True")]
        public bool columns_AttachmentsList_Name {
            get {
                return ((bool)(this["columns_AttachmentsList_Name"]));
            }
            set {
                this["columns_AttachmentsList_Name"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("True")]
        public bool columns_AttachmentsList_UserFullname {
            get {
                return ((bool)(this["columns_AttachmentsList_UserFullname"]));
            }
            set {
                this["columns_AttachmentsList_UserFullname"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("True")]
        public bool columns_AttachmentsList_Instance {
            get {
                return ((bool)(this["columns_AttachmentsList_Instance"]));
            }
            set {
                this["columns_AttachmentsList_Instance"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("pl")]
        public string Language {
            get {
                return ((string)(this["Language"]));
            }
            set {
                this["Language"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("#FF44CCCC")]
        public string config_Stores_PanelColor {
            get {
                return ((string)(this["config_Stores_PanelColor"]));
            }
            set {
                this["config_Stores_PanelColor"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("#FF99AABB")]
        public string config_Users_PanelColor {
            get {
                return ((string)(this["config_Users_PanelColor"]));
            }
            set {
                this["config_Users_PanelColor"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("#FFBB9966")]
        public string config_Employees_PanelColor {
            get {
                return ((string)(this["config_Employees_PanelColor"]));
            }
            set {
                this["config_Employees_PanelColor"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("#FFEEAA33")]
        public string config_AttributesClasses_PanelColor {
            get {
                return ((string)(this["config_AttributesClasses_PanelColor"]));
            }
            set {
                this["config_AttributesClasses_PanelColor"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("#FFEEEE55")]
        public string config_Attachments_PanelColor {
            get {
                return ((string)(this["config_Attachments_PanelColor"]));
            }
            set {
                this["config_Attachments_PanelColor"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("#FF44CCCC")]
        public string config_Logs_PanelColor {
            get {
                return ((string)(this["config_Logs_PanelColor"]));
            }
            set {
                this["config_Logs_PanelColor"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("#FF33AAEE")]
        public string config_Groups_PanelColor {
            get {
                return ((string)(this["config_Groups_PanelColor"]));
            }
            set {
                this["config_Groups_PanelColor"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("#FFFF69B4")]
        public string config_Community_PanelColor {
            get {
                return ((string)(this["config_Community_PanelColor"]));
            }
            set {
                this["config_Community_PanelColor"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool config_ExpandGroups {
            get {
                return ((bool)(this["config_ExpandGroups"]));
            }
            set {
                this["config_ExpandGroups"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("True")]
        public bool config_ShowButtonTexts {
            get {
                return ((bool)(this["config_ShowButtonTexts"]));
            }
            set {
                this["config_ShowButtonTexts"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("True")]
        public string columns_DocumentsList_ContractorName {
            get {
                return ((string)(this["columns_DocumentsList_ContractorName"]));
            }
            set {
                this["columns_DocumentsList_ContractorName"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("#FFEEEE55")]
        public string config_Contractors_PanelColor1 {
            get {
                return ((string)(this["config_Contractors_PanelColor1"]));
            }
            set {
                this["config_Contractors_PanelColor1"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public string columns_ContractorsList_ID {
            get {
                return ((string)(this["columns_ContractorsList_ID"]));
            }
            set {
                this["columns_ContractorsList_ID"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("True")]
        public string columns_ContractorsList_Codename {
            get {
                return ((string)(this["columns_ContractorsList_Codename"]));
            }
            set {
                this["columns_ContractorsList_Codename"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("True")]
        public string columns_ContractorsList_Name {
            get {
                return ((string)(this["columns_ContractorsList_Name"]));
            }
            set {
                this["columns_ContractorsList_Name"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("True")]
        public string columns_ContractorsList_Branch {
            get {
                return ((string)(this["columns_ContractorsList_Branch"]));
            }
            set {
                this["columns_ContractorsList_Branch"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public string columns_ContractorsList_NIP {
            get {
                return ((string)(this["columns_ContractorsList_NIP"]));
            }
            set {
                this["columns_ContractorsList_NIP"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public string columns_ContractorsList_REGON {
            get {
                return ((string)(this["columns_ContractorsList_REGON"]));
            }
            set {
                this["columns_ContractorsList_REGON"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public string columns_ContractorsList_Postcode {
            get {
                return ((string)(this["columns_ContractorsList_Postcode"]));
            }
            set {
                this["columns_ContractorsList_Postcode"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("True")]
        public string columns_ContractorsList_City {
            get {
                return ((string)(this["columns_ContractorsList_City"]));
            }
            set {
                this["columns_ContractorsList_City"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("True")]
        public string columns_ContractorsList_Address {
            get {
                return ((string)(this["columns_ContractorsList_Address"]));
            }
            set {
                this["columns_ContractorsList_Address"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute(@"<?xml version=""1.0"" encoding=""utf-16""?>
<ArrayOfString xmlns:xsi=""http://www.w3.org/2001/XMLSchema-instance"" xmlns:xsd=""http://www.w3.org/2001/XMLSchema"">
  <string>c.codename</string>
  <string>False</string>
  <string>c.name</string>
  <string>False</string>
  <string>50</string>
</ArrayOfString>")]
        public global::System.Collections.Specialized.StringCollection sorting_ContractorsList {
            get {
                return ((global::System.Collections.Specialized.StringCollection)(this["sorting_ContractorsList"]));
            }
            set {
                this["sorting_ContractorsList"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public string columns_ContractorsList_Icon {
            get {
                return ((string)(this["columns_ContractorsList_Icon"]));
            }
            set {
                this["columns_ContractorsList_Icon"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute(@"<?xml version=""1.0"" encoding=""utf-16""?>
<ArrayOfString xmlns:xsi=""http://www.w3.org/2001/XMLSchema-instance"" xmlns:xsd=""http://www.w3.org/2001/XMLSchema"">
  <string>v.register</string>
  <string>False</string>
  <string>v.brand</string>
  <string>False</string>
  <string>50</string>
</ArrayOfString>")]
        public global::System.Collections.Specialized.StringCollection sorting_VehiclesList {
            get {
                return ((global::System.Collections.Specialized.StringCollection)(this["sorting_VehiclesList"]));
            }
            set {
                this["sorting_VehiclesList"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("#FF55DD55")]
        public string config_Vehicles_PanelColor {
            get {
                return ((string)(this["config_Vehicles_PanelColor"]));
            }
            set {
                this["config_Vehicles_PanelColor"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool columns_VehiclesList_ID {
            get {
                return ((bool)(this["columns_VehiclesList_ID"]));
            }
            set {
                this["columns_VehiclesList_ID"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("True")]
        public bool columns_VehiclesList_Register {
            get {
                return ((bool)(this["columns_VehiclesList_Register"]));
            }
            set {
                this["columns_VehiclesList_Register"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("True")]
        public bool columns_VehiclesList_Brand {
            get {
                return ((bool)(this["columns_VehiclesList_Brand"]));
            }
            set {
                this["columns_VehiclesList_Brand"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("True")]
        public bool columns_VehiclesList_Model {
            get {
                return ((bool)(this["columns_VehiclesList_Model"]));
            }
            set {
                this["columns_VehiclesList_Model"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("True")]
        public bool columns_VehiclesList_Capacity {
            get {
                return ((bool)(this["columns_VehiclesList_Capacity"]));
            }
            set {
                this["columns_VehiclesList_Capacity"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("True")]
        public bool columns_VehiclesList_Forwarder {
            get {
                return ((bool)(this["columns_VehiclesList_Forwarder"]));
            }
            set {
                this["columns_VehiclesList_Forwarder"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("True")]
        public bool columns_VehiclesList_Driver {
            get {
                return ((bool)(this["columns_VehiclesList_Driver"]));
            }
            set {
                this["columns_VehiclesList_Driver"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool columns_VehiclesList_ProdYear {
            get {
                return ((bool)(this["columns_VehiclesList_ProdYear"]));
            }
            set {
                this["columns_VehiclesList_ProdYear"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool columns_VehiclesList_Icon {
            get {
                return ((bool)(this["columns_VehiclesList_Icon"]));
            }
            set {
                this["columns_VehiclesList_Icon"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("True")]
        public bool config_ShowButtonWithText {
            get {
                return ((bool)(this["config_ShowButtonWithText"]));
            }
            set {
                this["config_ShowButtonWithText"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("#FF444444")]
        public string ThemeColor {
            get {
                return ((string)(this["ThemeColor"]));
            }
            set {
                this["ThemeColor"] = value;
            }
        }
    }
}
