//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WBZ.Properties {
    
    
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.VisualStudio.Editors.SettingsDesigner.SettingsSingleFileGenerator", "16.10.0.0")]
    internal sealed partial class Settings : global::System.Configuration.ApplicationSettingsBase {
        
        private static Settings defaultInstance = ((Settings)(global::System.Configuration.ApplicationSettingsBase.Synchronized(new Settings())));
        
        public static Settings Default {
            get {
                return defaultInstance;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string apiUrl {
            get {
                return ((string)(this["apiUrl"]));
            }
            set {
                this["apiUrl"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string Login_Username {
            get {
                return ((string)(this["Login_Username"]));
            }
            set {
                this["Login_Username"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string Login_Password {
            get {
                return ((string)(this["Login_Password"]));
            }
            set {
                this["Login_Password"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string Login_Database {
            get {
                return ((string)(this["Login_Database"]));
            }
            set {
                this["Login_Database"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("True")]
        public bool Login_RememberMe {
            get {
                return ((bool)(this["Login_RememberMe"]));
            }
            set {
                this["Login_RememberMe"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("1")]
        public byte config_TitleBarStyle {
            get {
                return ((byte)(this["config_TitleBarStyle"]));
            }
            set {
                this["config_TitleBarStyle"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("#FF444444")]
        public string panelColor_Admin {
            get {
                return ((string)(this["panelColor_Admin"]));
            }
            set {
                this["panelColor_Admin"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("#FF33AAEE")]
        public string panelColor_Documents {
            get {
                return ((string)(this["panelColor_Documents"]));
            }
            set {
                this["panelColor_Documents"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool columns_DocumentsList_ID {
            get {
                return ((bool)(this["columns_DocumentsList_ID"]));
            }
            set {
                this["columns_DocumentsList_ID"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("True")]
        public bool columns_DocumentsList_Store {
            get {
                return ((bool)(this["columns_DocumentsList_Store"]));
            }
            set {
                this["columns_DocumentsList_Store"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("True")]
        public bool columns_DocumentsList_Type {
            get {
                return ((bool)(this["columns_DocumentsList_Type"]));
            }
            set {
                this["columns_DocumentsList_Type"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("True")]
        public bool columns_DocumentsList_Name {
            get {
                return ((bool)(this["columns_DocumentsList_Name"]));
            }
            set {
                this["columns_DocumentsList_Name"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("True")]
        public bool columns_DocumentsList_PositionsCount {
            get {
                return ((bool)(this["columns_DocumentsList_PositionsCount"]));
            }
            set {
                this["columns_DocumentsList_PositionsCount"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("True")]
        public bool columns_DocumentsList_Weight {
            get {
                return ((bool)(this["columns_DocumentsList_Weight"]));
            }
            set {
                this["columns_DocumentsList_Weight"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("True")]
        public bool columns_DocumentsList_Cost {
            get {
                return ((bool)(this["columns_DocumentsList_Cost"]));
            }
            set {
                this["columns_DocumentsList_Cost"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("True")]
        public bool columns_DocumentsList_DateIssue {
            get {
                return ((bool)(this["columns_DocumentsList_DateIssue"]));
            }
            set {
                this["columns_DocumentsList_DateIssue"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool columns_StoresList_ID {
            get {
                return ((bool)(this["columns_StoresList_ID"]));
            }
            set {
                this["columns_StoresList_ID"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("True")]
        public bool columns_StoresList_Codename {
            get {
                return ((bool)(this["columns_StoresList_Codename"]));
            }
            set {
                this["columns_StoresList_Codename"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("True")]
        public bool columns_StoresList_Name {
            get {
                return ((bool)(this["columns_StoresList_Name"]));
            }
            set {
                this["columns_StoresList_Name"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool columns_StoresList_Postcode {
            get {
                return ((bool)(this["columns_StoresList_Postcode"]));
            }
            set {
                this["columns_StoresList_Postcode"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool columns_StoresList_City {
            get {
                return ((bool)(this["columns_StoresList_City"]));
            }
            set {
                this["columns_StoresList_City"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool columns_StoresList_Address {
            get {
                return ((bool)(this["columns_StoresList_Address"]));
            }
            set {
                this["columns_StoresList_Address"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("True")]
        public bool columns_StoresList_Amount {
            get {
                return ((bool)(this["columns_StoresList_Amount"]));
            }
            set {
                this["columns_StoresList_Amount"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("True")]
        public bool columns_StoresList_Reserved {
            get {
                return ((bool)(this["columns_StoresList_Reserved"]));
            }
            set {
                this["columns_StoresList_Reserved"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("#FF55DD55")]
        public string panelColor_Articles {
            get {
                return ((string)(this["panelColor_Articles"]));
            }
            set {
                this["panelColor_Articles"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool columns_ArticlesList_ID {
            get {
                return ((bool)(this["columns_ArticlesList_ID"]));
            }
            set {
                this["columns_ArticlesList_ID"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("True")]
        public bool columns_ArticlesList_Codename {
            get {
                return ((bool)(this["columns_ArticlesList_Codename"]));
            }
            set {
                this["columns_ArticlesList_Codename"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("True")]
        public bool columns_ArticlesList_Name {
            get {
                return ((bool)(this["columns_ArticlesList_Name"]));
            }
            set {
                this["columns_ArticlesList_Name"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("True")]
        public bool columns_ArticlesList_EAN {
            get {
                return ((bool)(this["columns_ArticlesList_EAN"]));
            }
            set {
                this["columns_ArticlesList_EAN"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("True")]
        public bool columns_ArticlesList_Measure {
            get {
                return ((bool)(this["columns_ArticlesList_Measure"]));
            }
            set {
                this["columns_ArticlesList_Measure"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("True")]
        public bool columns_ArticlesList_Amount {
            get {
                return ((bool)(this["columns_ArticlesList_Amount"]));
            }
            set {
                this["columns_ArticlesList_Amount"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("True")]
        public bool columns_ArticlesList_Reserved {
            get {
                return ((bool)(this["columns_ArticlesList_Reserved"]));
            }
            set {
                this["columns_ArticlesList_Reserved"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("#FFEEEE55")]
        public string panelColor_Contractors {
            get {
                return ((string)(this["panelColor_Contractors"]));
            }
            set {
                this["panelColor_Contractors"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("#FFEEAA33")]
        public string panelColor_Families {
            get {
                return ((string)(this["panelColor_Families"]));
            }
            set {
                this["panelColor_Families"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("#FFBB88DD")]
        public string panelColor_Stats {
            get {
                return ((string)(this["panelColor_Stats"]));
            }
            set {
                this["panelColor_Stats"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool columns_FamiliesList_ID {
            get {
                return ((bool)(this["columns_FamiliesList_ID"]));
            }
            set {
                this["columns_FamiliesList_ID"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool columns_FamiliesList_Declarant {
            get {
                return ((bool)(this["columns_FamiliesList_Declarant"]));
            }
            set {
                this["columns_FamiliesList_Declarant"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("True")]
        public bool columns_FamiliesList_Lastname {
            get {
                return ((bool)(this["columns_FamiliesList_Lastname"]));
            }
            set {
                this["columns_FamiliesList_Lastname"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("True")]
        public bool columns_FamiliesList_Members {
            get {
                return ((bool)(this["columns_FamiliesList_Members"]));
            }
            set {
                this["columns_FamiliesList_Members"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("True")]
        public bool columns_FamiliesList_City {
            get {
                return ((bool)(this["columns_FamiliesList_City"]));
            }
            set {
                this["columns_FamiliesList_City"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool columns_FamiliesList_Address {
            get {
                return ((bool)(this["columns_FamiliesList_Address"]));
            }
            set {
                this["columns_FamiliesList_Address"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool columns_FamiliesList_Postcode {
            get {
                return ((bool)(this["columns_FamiliesList_Postcode"]));
            }
            set {
                this["columns_FamiliesList_Postcode"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("True")]
        public bool columns_FamiliesList_DonationWeight {
            get {
                return ((bool)(this["columns_FamiliesList_DonationWeight"]));
            }
            set {
                this["columns_FamiliesList_DonationWeight"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("True")]
        public bool columns_FamiliesList_Status {
            get {
                return ((bool)(this["columns_FamiliesList_Status"]));
            }
            set {
                this["columns_FamiliesList_Status"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("True")]
        public bool columns_FamiliesList_DonationLast {
            get {
                return ((bool)(this["columns_FamiliesList_DonationLast"]));
            }
            set {
                this["columns_FamiliesList_DonationLast"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("smtp.gmail.com")]
        public string config_Email_Host {
            get {
                return ((string)(this["config_Email_Host"]));
            }
            set {
                this["config_Email_Host"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("587")]
        public int config_Email_Port {
            get {
                return ((int)(this["config_Email_Port"]));
            }
            set {
                this["config_Email_Port"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("wbz.email.testowy@gmail.com")]
        public string config_Email_Email {
            get {
                return ((string)(this["config_Email_Email"]));
            }
            set {
                this["config_Email_Email"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("COM5")]
        public string config_GSM_com {
            get {
                return ((string)(this["config_GSM_com"]));
            }
            set {
                this["config_GSM_com"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("WBZ, Twoja paczka jest do odebrania. ")]
        public string config_GSM_message {
            get {
                return ((string)(this["config_GSM_message"]));
            }
            set {
                this["config_GSM_message"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string config_Email_Password {
            get {
                return ((string)(this["config_Email_Password"]));
            }
            set {
                this["config_Email_Password"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("wbztest.ddns.net")]
        public string conn_server {
            get {
                return ((string)(this["conn_server"]));
            }
            set {
                this["conn_server"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("5432")]
        public int conn_port {
            get {
                return ((int)(this["conn_port"]));
            }
            set {
                this["conn_port"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("wbz")]
        public string conn_database {
            get {
                return ((string)(this["conn_database"]));
            }
            set {
                this["conn_database"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string conn_userID {
            get {
                return ((string)(this["conn_userID"]));
            }
            set {
                this["conn_userID"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string conn_password {
            get {
                return ((string)(this["conn_password"]));
            }
            set {
                this["conn_password"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("#FFEE5555")]
        public string panelColor_Distributions {
            get {
                return ((string)(this["panelColor_Distributions"]));
            }
            set {
                this["panelColor_Distributions"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool columns_DistributionsList_ID {
            get {
                return ((bool)(this["columns_DistributionsList_ID"]));
            }
            set {
                this["columns_DistributionsList_ID"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("True")]
        public bool columns_DistributionsList_Name {
            get {
                return ((bool)(this["columns_DistributionsList_Name"]));
            }
            set {
                this["columns_DistributionsList_Name"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("True")]
        public bool columns_DistributionsList_FamiliesCount {
            get {
                return ((bool)(this["columns_DistributionsList_FamiliesCount"]));
            }
            set {
                this["columns_DistributionsList_FamiliesCount"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool columns_DistributionsList_MembersCount {
            get {
                return ((bool)(this["columns_DistributionsList_MembersCount"]));
            }
            set {
                this["columns_DistributionsList_MembersCount"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("True")]
        public bool columns_DistributionsList_PositionsCount {
            get {
                return ((bool)(this["columns_DistributionsList_PositionsCount"]));
            }
            set {
                this["columns_DistributionsList_PositionsCount"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("True")]
        public bool columns_DistributionsList_Weight {
            get {
                return ((bool)(this["columns_DistributionsList_Weight"]));
            }
            set {
                this["columns_DistributionsList_Weight"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("True")]
        public bool columns_DistributionsList_DateReal {
            get {
                return ((bool)(this["columns_DistributionsList_DateReal"]));
            }
            set {
                this["columns_DistributionsList_DateReal"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("True")]
        public bool UpgradeRequired {
            get {
                return ((bool)(this["UpgradeRequired"]));
            }
            set {
                this["UpgradeRequired"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool columns_UsersList_ID {
            get {
                return ((bool)(this["columns_UsersList_ID"]));
            }
            set {
                this["columns_UsersList_ID"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("True")]
        public bool columns_UsersList_Fullname {
            get {
                return ((bool)(this["columns_UsersList_Fullname"]));
            }
            set {
                this["columns_UsersList_Fullname"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("True")]
        public bool columns_UsersList_Email {
            get {
                return ((bool)(this["columns_UsersList_Email"]));
            }
            set {
                this["columns_UsersList_Email"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("True")]
        public bool columns_UsersList_Phone {
            get {
                return ((bool)(this["columns_UsersList_Phone"]));
            }
            set {
                this["columns_UsersList_Phone"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool columns_LogsList_ID {
            get {
                return ((bool)(this["columns_LogsList_ID"]));
            }
            set {
                this["columns_LogsList_ID"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("True")]
        public bool columns_LogsList_User {
            get {
                return ((bool)(this["columns_LogsList_User"]));
            }
            set {
                this["columns_LogsList_User"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("True")]
        public bool columns_LogsList_Module {
            get {
                return ((bool)(this["columns_LogsList_Module"]));
            }
            set {
                this["columns_LogsList_Module"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("True")]
        public bool columns_LogsList_Obj {
            get {
                return ((bool)(this["columns_LogsList_Obj"]));
            }
            set {
                this["columns_LogsList_Obj"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("True")]
        public bool columns_LogsList_Content {
            get {
                return ((bool)(this["columns_LogsList_Content"]));
            }
            set {
                this["columns_LogsList_Content"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("True")]
        public bool columns_LogsList_DateTime {
            get {
                return ((bool)(this["columns_LogsList_DateTime"]));
            }
            set {
                this["columns_LogsList_DateTime"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool columns_EmployeesList_ID {
            get {
                return ((bool)(this["columns_EmployeesList_ID"]));
            }
            set {
                this["columns_EmployeesList_ID"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("True")]
        public bool columns_EmployeesList_Fullname {
            get {
                return ((bool)(this["columns_EmployeesList_Fullname"]));
            }
            set {
                this["columns_EmployeesList_Fullname"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool columns_EmployeesList_Department {
            get {
                return ((bool)(this["columns_EmployeesList_Department"]));
            }
            set {
                this["columns_EmployeesList_Department"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool columns_EmployeesList_Position {
            get {
                return ((bool)(this["columns_EmployeesList_Position"]));
            }
            set {
                this["columns_EmployeesList_Position"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("True")]
        public bool columns_EmployeesList_Email {
            get {
                return ((bool)(this["columns_EmployeesList_Email"]));
            }
            set {
                this["columns_EmployeesList_Email"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("True")]
        public bool columns_EmployeesList_Phone {
            get {
                return ((bool)(this["columns_EmployeesList_Phone"]));
            }
            set {
                this["columns_EmployeesList_Phone"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool columns_EmployeesList_Postcode {
            get {
                return ((bool)(this["columns_EmployeesList_Postcode"]));
            }
            set {
                this["columns_EmployeesList_Postcode"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool columns_EmployeesList_City {
            get {
                return ((bool)(this["columns_EmployeesList_City"]));
            }
            set {
                this["columns_EmployeesList_City"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool columns_EmployeesList_Address {
            get {
                return ((bool)(this["columns_EmployeesList_Address"]));
            }
            set {
                this["columns_EmployeesList_Address"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("<?xml version=\"1.0\" encoding=\"utf-16\"?>\r\n<ArrayOfString xmlns:xsi=\"http://www.w3." +
            "org/2001/XMLSchema-instance\" xmlns:xsd=\"http://www.w3.org/2001/XMLSchema\">\r\n  <s" +
            "tring>emp.lastname asc</string>\r\n  <string>emp.forename asc</string>\r\n</ArrayOfS" +
            "tring>")]
        public global::System.Collections.Specialized.StringCollection sorting_Employees {
            get {
                return ((global::System.Collections.Specialized.StringCollection)(this["sorting_Employees"]));
            }
            set {
                this["sorting_Employees"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("<?xml version=\"1.0\" encoding=\"utf-16\"?>\r\n<ArrayOfString xmlns:xsi=\"http://www.w3." +
            "org/2001/XMLSchema-instance\" xmlns:xsd=\"http://www.w3.org/2001/XMLSchema\">\r\n  <s" +
            "tring>use.lastname asc</string>\r\n  <string>use.forename asc</string>\r\n</ArrayOfS" +
            "tring>")]
        public global::System.Collections.Specialized.StringCollection sorting_Users {
            get {
                return ((global::System.Collections.Specialized.StringCollection)(this["sorting_Users"]));
            }
            set {
                this["sorting_Users"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("<?xml version=\"1.0\" encoding=\"utf-16\"?>\r\n<ArrayOfString xmlns:xsi=\"http://www.w3." +
            "org/2001/XMLSchema-instance\" xmlns:xsd=\"http://www.w3.org/2001/XMLSchema\">\r\n  <s" +
            "tring>art.codename asc</string>\r\n  <string>art.name asc</string>\r\n</ArrayOfStrin" +
            "g>")]
        public global::System.Collections.Specialized.StringCollection sorting_Articles {
            get {
                return ((global::System.Collections.Specialized.StringCollection)(this["sorting_Articles"]));
            }
            set {
                this["sorting_Articles"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("<?xml version=\"1.0\" encoding=\"utf-16\"?>\r\n<ArrayOfString xmlns:xsi=\"http://www.w3." +
            "org/2001/XMLSchema-instance\" xmlns:xsd=\"http://www.w3.org/2001/XMLSchema\">\r\n  <s" +
            "tring>sto.codename asc</string>\r\n  <string>sto.name asc</string>\r\n</ArrayOfStrin" +
            "g>")]
        public global::System.Collections.Specialized.StringCollection sorting_Stores {
            get {
                return ((global::System.Collections.Specialized.StringCollection)(this["sorting_Stores"]));
            }
            set {
                this["sorting_Stores"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("<?xml version=\"1.0\" encoding=\"utf-16\"?>\r\n<ArrayOfString xmlns:xsi=\"http://www.w3." +
            "org/2001/XMLSchema-instance\" xmlns:xsd=\"http://www.w3.org/2001/XMLSchema\">\r\n  <s" +
            "tring>fam.lastname asc</string>\r\n  <string>fam.city asc</string>\r\n</ArrayOfStrin" +
            "g>")]
        public global::System.Collections.Specialized.StringCollection sorting_Families {
            get {
                return ((global::System.Collections.Specialized.StringCollection)(this["sorting_Families"]));
            }
            set {
                this["sorting_Families"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("<?xml version=\"1.0\" encoding=\"utf-16\"?>\r\n<ArrayOfString xmlns:xsi=\"http://www.w3." +
            "org/2001/XMLSchema-instance\" xmlns:xsd=\"http://www.w3.org/2001/XMLSchema\">\r\n  <s" +
            "tring>doc.dateissue asc</string>\r\n  <string>doc.name asc</string>\r\n</ArrayOfStri" +
            "ng>")]
        public global::System.Collections.Specialized.StringCollection sorting_Documents {
            get {
                return ((global::System.Collections.Specialized.StringCollection)(this["sorting_Documents"]));
            }
            set {
                this["sorting_Documents"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("<?xml version=\"1.0\" encoding=\"utf-16\"?>\r\n<ArrayOfString xmlns:xsi=\"http://www.w3." +
            "org/2001/XMLSchema-instance\" xmlns:xsd=\"http://www.w3.org/2001/XMLSchema\">\r\n  <s" +
            "tring>dis.datereal asc</string>\r\n  <string>dis.name asc</string>\r\n</ArrayOfStrin" +
            "g>")]
        public global::System.Collections.Specialized.StringCollection sorting_Distributions {
            get {
                return ((global::System.Collections.Specialized.StringCollection)(this["sorting_Distributions"]));
            }
            set {
                this["sorting_Distributions"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("<?xml version=\"1.0\" encoding=\"utf-16\"?>\r\n<ArrayOfString xmlns:xsi=\"http://www.w3." +
            "org/2001/XMLSchema-instance\" xmlns:xsd=\"http://www.w3.org/2001/XMLSchema\">\r\n  <s" +
            "tring>log.datetime desc</string>\r\n</ArrayOfString>")]
        public global::System.Collections.Specialized.StringCollection sorting_Logs {
            get {
                return ((global::System.Collections.Specialized.StringCollection)(this["sorting_Logs"]));
            }
            set {
                this["sorting_Logs"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("<?xml version=\"1.0\" encoding=\"utf-16\"?>\r\n<ArrayOfString xmlns:xsi=\"http://www.w3." +
            "org/2001/XMLSchema-instance\" xmlns:xsd=\"http://www.w3.org/2001/XMLSchema\">\r\n  <s" +
            "tring>atc.module asc</string>\r\n  <string>atc.name asc</string>\r\n</ArrayOfString>" +
            "")]
        public global::System.Collections.Specialized.StringCollection sorting_AttributesClasses {
            get {
                return ((global::System.Collections.Specialized.StringCollection)(this["sorting_AttributesClasses"]));
            }
            set {
                this["sorting_AttributesClasses"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("<?xml version=\"1.0\" encoding=\"utf-16\"?>\r\n<ArrayOfString xmlns:xsi=\"http://www.w3." +
            "org/2001/XMLSchema-instance\" xmlns:xsd=\"http://www.w3.org/2001/XMLSchema\">\r\n  <s" +
            "tring>gro.module asc</string>\r\n  <string>gro.name asc</string>\r\n</ArrayOfString>" +
            "")]
        public global::System.Collections.Specialized.StringCollection sorting_Groups {
            get {
                return ((global::System.Collections.Specialized.StringCollection)(this["sorting_Groups"]));
            }
            set {
                this["sorting_Groups"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("<?xml version=\"1.0\" encoding=\"utf-16\"?>\r\n<ArrayOfString xmlns:xsi=\"http://www.w3." +
            "org/2001/XMLSchema-instance\" xmlns:xsd=\"http://www.w3.org/2001/XMLSchema\">\r\n  <s" +
            "tring>att.module asc</string>\r\n  <string>att.name asc</string>\r\n</ArrayOfString>" +
            "")]
        public global::System.Collections.Specialized.StringCollection sorting_Gallery {
            get {
                return ((global::System.Collections.Specialized.StringCollection)(this["sorting_Gallery"]));
            }
            set {
                this["sorting_Gallery"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool columns_EmployeesList_Icon {
            get {
                return ((bool)(this["columns_EmployeesList_Icon"]));
            }
            set {
                this["columns_EmployeesList_Icon"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool columns_ArticlesList_Icon {
            get {
                return ((bool)(this["columns_ArticlesList_Icon"]));
            }
            set {
                this["columns_ArticlesList_Icon"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool columns_StoresList_Icon {
            get {
                return ((bool)(this["columns_StoresList_Icon"]));
            }
            set {
                this["columns_StoresList_Icon"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool columns_AttributesClassesList_Icon {
            get {
                return ((bool)(this["columns_AttributesClassesList_Icon"]));
            }
            set {
                this["columns_AttributesClassesList_Icon"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool columns_DistributionsList_Icon {
            get {
                return ((bool)(this["columns_DistributionsList_Icon"]));
            }
            set {
                this["columns_DistributionsList_Icon"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool columns_DocumentsList_Icon {
            get {
                return ((bool)(this["columns_DocumentsList_Icon"]));
            }
            set {
                this["columns_DocumentsList_Icon"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool columns_FamiliesList_Icon {
            get {
                return ((bool)(this["columns_FamiliesList_Icon"]));
            }
            set {
                this["columns_FamiliesList_Icon"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool columns_AttributesClassesList_ID {
            get {
                return ((bool)(this["columns_AttributesClassesList_ID"]));
            }
            set {
                this["columns_AttributesClassesList_ID"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("True")]
        public bool columns_AttributesClassesList_Module {
            get {
                return ((bool)(this["columns_AttributesClassesList_Module"]));
            }
            set {
                this["columns_AttributesClassesList_Module"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("True")]
        public bool columns_AttributesClassesList_Name {
            get {
                return ((bool)(this["columns_AttributesClassesList_Name"]));
            }
            set {
                this["columns_AttributesClassesList_Name"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("True")]
        public bool columns_AttributesClassesList_Type {
            get {
                return ((bool)(this["columns_AttributesClassesList_Type"]));
            }
            set {
                this["columns_AttributesClassesList_Type"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool columns_AttributesClassesList_Values {
            get {
                return ((bool)(this["columns_AttributesClassesList_Values"]));
            }
            set {
                this["columns_AttributesClassesList_Values"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool columns_AttributesClassesList_Required {
            get {
                return ((bool)(this["columns_AttributesClassesList_Required"]));
            }
            set {
                this["columns_AttributesClassesList_Required"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("<?xml version=\"1.0\" encoding=\"utf-16\"?>\r\n<ArrayOfString xmlns:xsi=\"http://www.w3." +
            "org/2001/XMLSchema-instance\" xmlns:xsd=\"http://www.w3.org/2001/XMLSchema\">\r\n  <s" +
            "tring>att.module asc</string>\r\n  <string>att.name asc</string>\r\n</ArrayOfString>" +
            "")]
        public global::System.Collections.Specialized.StringCollection sorting_Attachments {
            get {
                return ((global::System.Collections.Specialized.StringCollection)(this["sorting_Attachments"]));
            }
            set {
                this["sorting_Attachments"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool columns_AttachmentsList_ID {
            get {
                return ((bool)(this["columns_AttachmentsList_ID"]));
            }
            set {
                this["columns_AttachmentsList_ID"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("True")]
        public bool columns_AttachmentsList_Module {
            get {
                return ((bool)(this["columns_AttachmentsList_Module"]));
            }
            set {
                this["columns_AttachmentsList_Module"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("True")]
        public bool columns_AttachmentsList_Name {
            get {
                return ((bool)(this["columns_AttachmentsList_Name"]));
            }
            set {
                this["columns_AttachmentsList_Name"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("True")]
        public bool columns_AttachmentsList_User {
            get {
                return ((bool)(this["columns_AttachmentsList_User"]));
            }
            set {
                this["columns_AttachmentsList_User"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("True")]
        public bool columns_AttachmentsList_Instance {
            get {
                return ((bool)(this["columns_AttachmentsList_Instance"]));
            }
            set {
                this["columns_AttachmentsList_Instance"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("pl")]
        public string Language {
            get {
                return ((string)(this["Language"]));
            }
            set {
                this["Language"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("#FF44CCCC")]
        public string panelColor_Stores {
            get {
                return ((string)(this["panelColor_Stores"]));
            }
            set {
                this["panelColor_Stores"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("#FF99AABB")]
        public string panelColor_Users {
            get {
                return ((string)(this["panelColor_Users"]));
            }
            set {
                this["panelColor_Users"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("#FFBB9966")]
        public string panelColor_Employees {
            get {
                return ((string)(this["panelColor_Employees"]));
            }
            set {
                this["panelColor_Employees"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("#FFEEAA33")]
        public string panelColor_AttributesClasses {
            get {
                return ((string)(this["panelColor_AttributesClasses"]));
            }
            set {
                this["panelColor_AttributesClasses"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("#FFEEEE55")]
        public string panelColor_Attachments {
            get {
                return ((string)(this["panelColor_Attachments"]));
            }
            set {
                this["panelColor_Attachments"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("#FF44CCCC")]
        public string panelColor_Logs {
            get {
                return ((string)(this["panelColor_Logs"]));
            }
            set {
                this["panelColor_Logs"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("#FF33AAEE")]
        public string panelColor_Groups {
            get {
                return ((string)(this["panelColor_Groups"]));
            }
            set {
                this["panelColor_Groups"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("#FFFF69B4")]
        public string panelColor_Community {
            get {
                return ((string)(this["panelColor_Community"]));
            }
            set {
                this["panelColor_Community"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool config_ExpandGroups {
            get {
                return ((bool)(this["config_ExpandGroups"]));
            }
            set {
                this["config_ExpandGroups"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("True")]
        public bool config_ShowButtonTexts {
            get {
                return ((bool)(this["config_ShowButtonTexts"]));
            }
            set {
                this["config_ShowButtonTexts"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("True")]
        public string columns_DocumentsList_ContractorName {
            get {
                return ((string)(this["columns_DocumentsList_ContractorName"]));
            }
            set {
                this["columns_DocumentsList_ContractorName"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public string columns_ContractorsList_ID {
            get {
                return ((string)(this["columns_ContractorsList_ID"]));
            }
            set {
                this["columns_ContractorsList_ID"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("True")]
        public string columns_ContractorsList_Codename {
            get {
                return ((string)(this["columns_ContractorsList_Codename"]));
            }
            set {
                this["columns_ContractorsList_Codename"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("True")]
        public string columns_ContractorsList_Name {
            get {
                return ((string)(this["columns_ContractorsList_Name"]));
            }
            set {
                this["columns_ContractorsList_Name"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("True")]
        public string columns_ContractorsList_Branch {
            get {
                return ((string)(this["columns_ContractorsList_Branch"]));
            }
            set {
                this["columns_ContractorsList_Branch"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public string columns_ContractorsList_NIP {
            get {
                return ((string)(this["columns_ContractorsList_NIP"]));
            }
            set {
                this["columns_ContractorsList_NIP"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public string columns_ContractorsList_REGON {
            get {
                return ((string)(this["columns_ContractorsList_REGON"]));
            }
            set {
                this["columns_ContractorsList_REGON"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public string columns_ContractorsList_Postcode {
            get {
                return ((string)(this["columns_ContractorsList_Postcode"]));
            }
            set {
                this["columns_ContractorsList_Postcode"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("True")]
        public string columns_ContractorsList_City {
            get {
                return ((string)(this["columns_ContractorsList_City"]));
            }
            set {
                this["columns_ContractorsList_City"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("True")]
        public string columns_ContractorsList_Address {
            get {
                return ((string)(this["columns_ContractorsList_Address"]));
            }
            set {
                this["columns_ContractorsList_Address"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("<?xml version=\"1.0\" encoding=\"utf-16\"?>\r\n<ArrayOfString xmlns:xsi=\"http://www.w3." +
            "org/2001/XMLSchema-instance\" xmlns:xsd=\"http://www.w3.org/2001/XMLSchema\">\r\n  <s" +
            "tring>cnt.codename asc</string>\r\n  <string>cnt.name asc</string>\r\n</ArrayOfStrin" +
            "g>")]
        public global::System.Collections.Specialized.StringCollection sorting_Contractors {
            get {
                return ((global::System.Collections.Specialized.StringCollection)(this["sorting_Contractors"]));
            }
            set {
                this["sorting_Contractors"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public string columns_ContractorsList_Icon {
            get {
                return ((string)(this["columns_ContractorsList_Icon"]));
            }
            set {
                this["columns_ContractorsList_Icon"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("<?xml version=\"1.0\" encoding=\"utf-16\"?>\r\n<ArrayOfString xmlns:xsi=\"http://www.w3." +
            "org/2001/XMLSchema-instance\" xmlns:xsd=\"http://www.w3.org/2001/XMLSchema\">\r\n  <s" +
            "tring>veh.register asc</string>\r\n  <string>veh.brand asc</string>\r\n</ArrayOfStri" +
            "ng>")]
        public global::System.Collections.Specialized.StringCollection sorting_Vehicles {
            get {
                return ((global::System.Collections.Specialized.StringCollection)(this["sorting_Vehicles"]));
            }
            set {
                this["sorting_Vehicles"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("#FF55DD55")]
        public string panelColor_Vehicles {
            get {
                return ((string)(this["panelColor_Vehicles"]));
            }
            set {
                this["panelColor_Vehicles"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool columns_VehiclesList_ID {
            get {
                return ((bool)(this["columns_VehiclesList_ID"]));
            }
            set {
                this["columns_VehiclesList_ID"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("True")]
        public bool columns_VehiclesList_Register {
            get {
                return ((bool)(this["columns_VehiclesList_Register"]));
            }
            set {
                this["columns_VehiclesList_Register"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("True")]
        public bool columns_VehiclesList_Brand {
            get {
                return ((bool)(this["columns_VehiclesList_Brand"]));
            }
            set {
                this["columns_VehiclesList_Brand"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("True")]
        public bool columns_VehiclesList_Model {
            get {
                return ((bool)(this["columns_VehiclesList_Model"]));
            }
            set {
                this["columns_VehiclesList_Model"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("True")]
        public bool columns_VehiclesList_Capacity {
            get {
                return ((bool)(this["columns_VehiclesList_Capacity"]));
            }
            set {
                this["columns_VehiclesList_Capacity"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("True")]
        public bool columns_VehiclesList_Forwarder {
            get {
                return ((bool)(this["columns_VehiclesList_Forwarder"]));
            }
            set {
                this["columns_VehiclesList_Forwarder"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("True")]
        public bool columns_VehiclesList_Driver {
            get {
                return ((bool)(this["columns_VehiclesList_Driver"]));
            }
            set {
                this["columns_VehiclesList_Driver"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool columns_VehiclesList_ProdYear {
            get {
                return ((bool)(this["columns_VehiclesList_ProdYear"]));
            }
            set {
                this["columns_VehiclesList_ProdYear"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool columns_VehiclesList_Icon {
            get {
                return ((bool)(this["columns_VehiclesList_Icon"]));
            }
            set {
                this["columns_VehiclesList_Icon"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("True")]
        public bool config_ShowButtonWithText {
            get {
                return ((bool)(this["config_ShowButtonWithText"]));
            }
            set {
                this["config_ShowButtonWithText"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("#FF3C4B5A")]
        public string ThemeColor {
            get {
                return ((string)(this["ThemeColor"]));
            }
            set {
                this["ThemeColor"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("True")]
        public bool config_ShowHeaderWithText {
            get {
                return ((bool)(this["config_ShowHeaderWithText"]));
            }
            set {
                this["config_ShowHeaderWithText"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("#FF999999")]
        public string panelColor_Main {
            get {
                return ((string)(this["panelColor_Main"]));
            }
            set {
                this["panelColor_Main"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("#FFEEEE55")]
        public string panelColor_Icons {
            get {
                return ((string)(this["panelColor_Icons"]));
            }
            set {
                this["panelColor_Icons"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("<?xml version=\"1.0\" encoding=\"utf-16\"?>\r\n<ArrayOfString xmlns:xsi=\"http://www.w3." +
            "org/2001/XMLSchema-instance\" xmlns:xsd=\"http://www.w3.org/2001/XMLSchema\">\r\n  <s" +
            "tring>ico.module asc</string>\r\n  <string>ico.name asc</string>\r\n</ArrayOfString>" +
            "")]
        public global::System.Collections.Specialized.StringCollection sorting_Icons {
            get {
                return ((global::System.Collections.Specialized.StringCollection)(this["sorting_Icons"]));
            }
            set {
                this["sorting_Icons"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool columns_IconsList_ID {
            get {
                return ((bool)(this["columns_IconsList_ID"]));
            }
            set {
                this["columns_IconsList_ID"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("True")]
        public bool columns_IconsList_File {
            get {
                return ((bool)(this["columns_IconsList_File"]));
            }
            set {
                this["columns_IconsList_File"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("True")]
        public bool columns_IconsList_Module {
            get {
                return ((bool)(this["columns_IconsList_Module"]));
            }
            set {
                this["columns_IconsList_Module"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("True")]
        public bool columns_IconsList_Name {
            get {
                return ((bool)(this["columns_IconsList_Name"]));
            }
            set {
                this["columns_IconsList_Name"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool columns_IconsList_Format {
            get {
                return ((bool)(this["columns_IconsList_Format"]));
            }
            set {
                this["columns_IconsList_Format"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool columns_IconsList_Path {
            get {
                return ((bool)(this["columns_IconsList_Path"]));
            }
            set {
                this["columns_IconsList_Path"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool columns_IconsList_Height {
            get {
                return ((bool)(this["columns_IconsList_Height"]));
            }
            set {
                this["columns_IconsList_Height"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool columns_IconsList_Width {
            get {
                return ((bool)(this["columns_IconsList_Width"]));
            }
            set {
                this["columns_IconsList_Width"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("True")]
        public bool columns_IconsList_Size {
            get {
                return ((bool)(this["columns_IconsList_Size"]));
            }
            set {
                this["columns_IconsList_Size"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("50")]
        public int limit_Users {
            get {
                return ((int)(this["limit_Users"]));
            }
            set {
                this["limit_Users"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("50")]
        public int limit_Vehicles {
            get {
                return ((int)(this["limit_Vehicles"]));
            }
            set {
                this["limit_Vehicles"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("50")]
        public int limit_Stores {
            get {
                return ((int)(this["limit_Stores"]));
            }
            set {
                this["limit_Stores"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("50")]
        public int limit_Logs {
            get {
                return ((int)(this["limit_Logs"]));
            }
            set {
                this["limit_Logs"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("50")]
        public int limit_Icons {
            get {
                return ((int)(this["limit_Icons"]));
            }
            set {
                this["limit_Icons"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("50")]
        public int limit_Groups {
            get {
                return ((int)(this["limit_Groups"]));
            }
            set {
                this["limit_Groups"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("10")]
        public int limit_Gallery {
            get {
                return ((int)(this["limit_Gallery"]));
            }
            set {
                this["limit_Gallery"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("50")]
        public int limit_Families {
            get {
                return ((int)(this["limit_Families"]));
            }
            set {
                this["limit_Families"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("50")]
        public int limit_Employees {
            get {
                return ((int)(this["limit_Employees"]));
            }
            set {
                this["limit_Employees"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("50")]
        public int limit_Documents {
            get {
                return ((int)(this["limit_Documents"]));
            }
            set {
                this["limit_Documents"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("50")]
        public int limit_Distributions {
            get {
                return ((int)(this["limit_Distributions"]));
            }
            set {
                this["limit_Distributions"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("50")]
        public int limit_Contractors {
            get {
                return ((int)(this["limit_Contractors"]));
            }
            set {
                this["limit_Contractors"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("50")]
        public int limit_AttributesClasses {
            get {
                return ((int)(this["limit_AttributesClasses"]));
            }
            set {
                this["limit_AttributesClasses"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("50")]
        public int limit_Attachments {
            get {
                return ((int)(this["limit_Attachments"]));
            }
            set {
                this["limit_Attachments"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("50")]
        public int limit_Articles {
            get {
                return ((int)(this["limit_Articles"]));
            }
            set {
                this["limit_Articles"] = value;
            }
        }
    }
}
